apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: bzn3jl104-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.eedb4485-f7d6-4c04-a17b-2e528901a0b1.prod.konfluxeaas.com/rhtap/rhtap-qe-python:27101fed5e0fa44e3dcab7fba38f2e5d7c2aee1b@sha256:56622b56504d820ad070c3edc93d6583576f01f810543a63baff58735c47f93a
          name: container-image
